[plugins]
[plugins.chat]
api_key = ''
base_url = 'https://api.deepseek.com/v1'
bot_self_id = 0
owner_id = 0
prefs_path = './data/chat/user_prefs.json'

[plugins.emote]
data_path = 'data/images/è¡¨æƒ…'

[plugins.fortune]
storage = './data/fortune'

[plugins.image]
db_path = './data/images/index.json'
images_folder = './data/images'

[[plugins.image.categories]]
caption = 'ä»Šå¤©åƒè¿™ä¸ªå§ï¼ğŸœ'
commands = ['åƒä»€ä¹ˆ', 'ä»Šå¤©åƒå•¥', 'è¯¥åƒä»€ä¹ˆäº†']
count = 4
folder = 'åƒçš„'
grid_width = 750
message_template = 'ä»Šå¤©æˆ‘ä»¬æ¥ç‚¹ %s å§ï½ ğŸ˜‹'


[plugins.reply]
db_path = './data/reply.json'

[plugins.sticker]
db_path = './data/botsticker.json'
